apiVersion: v2
name: crud
description: "Fraeym CRUD: Easily create a CRUD API for your data"
type: application
version: 1.0.0-alpha.5 # Chart version
appVersion: "1.0.0-alpha.5" # Fraeym CRUD version
