apiVersion: v2
name: deployments
description: "Fraeym Deployments: Schema Deployments for Fraeym"
type: application
version: 1.0.0-alpha.9 # Chart version
appVersion: "1.0.0-alpha.9" # Fraeym Deployments version
