apiVersion: v2
name: projections
description: "Fraeym Projections: Projections for event sourced applications"
type: application
version: 0.2.11 # Chart version
appVersion: "0.39.11" # Fraeym Projections version
