apiVersion: v2
name: projections
description: "Fraeym Projections: Projections for event sourced applications"
type: application
version: 1.0.8 # Chart version
appVersion: "1.0.8" # Fraeym Projections version
