apiVersion: v2
name: projections
description: "Fraeym Projections: Projections for event sourced applications"
type: application
version: 0.2.12 # Chart version
appVersion: "0.39.12" # Fraeym Projections version
