apiVersion: v2
name: projections
description: "Fraeym Projections: Projections for event sourced applications"
type: application
version: 1.0.0-alpha.21 # Chart version
appVersion: "1.0.0-alpha.21" # Fraeym Projections version
